### ISSUE TITLE
Issue: Safety check failing with error - Unhandled exception happened: post_dump() got an unexpected keyword argument 'pass_many'

### ISSUE THREAD

**Issue by Rakeshmn1993** [pyupio/safety#711]
### Checklist

- [x] I agree to the terms within the [Safety Code of Conduct](https://github.com/pyupio/safety/blob/main/CODE_OF_CONDUCT.md).

### Safety version

safety-3.3.1-py3-none-any.whl)

### Python version

3.12

### Operating System

Ubuntu, MAC

### Describe the problem you'd like to have solved

From Jenkins, we are seeing this new error from today:
```
+ safety check --output text -r requirements.txt -r requirements-test.txt

+===========================================================================================================================================================================================+

DEPRECATED: this command (`check`) has been DEPRECATED, and will be unsupported beyond 01 June 2024.

We highly encourage switching to the new `scan` command which is easier to use, more powerful, and can be set up to mimic the deprecated command if required.

+===========================================================================================================================================================================================+

Unhandled exception happened: post_dump() got an unexpected keyword argument 'pass_many'
```
Tried via hook locally, it also failes with the same error.

### Describe the ideal solution

Not really sure

### What I Did

The scanning is failing with above error

**Comment by Hallocoos** [comment]
Also experiencing this issue in our pipelines.

```
safety check -i 67599,70612


+===========================================================================================================================================================================================+


DEPRECATED: this command (`check`) has been DEPRECATED, and will be unsupported beyond 01 June 2024.


We highly encourage switching to the new `scan` command which is easier to use, more powerful, and can be set up to mimic the deprecated command if required.


+===========================================================================================================================================================================================+


Unhandled exception happened: post_dump() got an unexpected keyword argument 'pass_many'
```

Nothing has changed on our pipelines since the last successful run.

**Comment by Atilova** [comment]
Seems, the issue lies in the newly released version marshmallow==4.0.0. Try using marshmallow==3.* which resolves the issue.

**Comment by ShortLegsFox** [comment]
> It seems the issue lies in the newly released marshmallow==4.0.0 package, which is required for the safety installation. Try pinning marshmallow==3.*, which resolves the issue.

Worked for me as well, thanks a lot !

**Comment by Rakeshmn1993** [comment]
Thank you all for the response! I tried to install marshmallow with the specified version:
```
python3 -m pip install marshmallow==3.14
Collecting marshmallow==3.14
  Downloading ..... marshmallow-3.14.0-py3-none-any.whl (47 kB)
Installing collected packages: marshmallow
Successfully installed marshmallow-3.14.0
```
But when I install safety, it requires the marshmallow version >= 3.15
```
Collecting marshmallow>=3.15.0 (from safety)
  Downloading ....

  Attempting uninstall: marshmallow
    Found existing installation: marshmallow 3.14.0
    Uninstalling marshmallow-3.14.0:
      Successfully uninstalled marshmallow-3.14.0
```
So, should I install the older version of safety here?

**Comment by Rakeshmn1993** [comment]
Ignore, I got it working with `marshmallow==3.26.1`
Thanks all!

**Comment by nbhoomika** [comment]
I am still facing issue can anyone comment what eaxctly we have to do for this i have safety 3.2.3 installed and with both marshmallow version am getting issue

**Comment by yeisonvargasf** [comment]
I've submitted a PR that fixes this issue with marshmallow 4.* compatibility:

In the meantime, you can work around this by **pinning marshmallow to any version lower** than `4.0.0`. We plan to remove `marshmallow` in future releases, as it is used only in a legacy feature for JSON exports.

To avoid this type of situation again, we are improving our pipeline and will soon test against development versions of our dependencies.

For those still experiencing problems:

1. Uninstall Safety if already installed: `pip uninstall safety`
2. Install marshmallow with a specific version: `pip install marshmallow==version` _where_ **version is any value lower than 4.0.0**
3. Install safety: `pip install safety`

This should resolve the "post_dump() got an unexpected keyword argument 'pass_many'" error until the next Safety CLI release (3.4.0), which will include the fix.
